#!/usr/bin/env python3
"""Build catalog.json from catalog.yaml, for the engine and for the webapp.

    python3 graph_db/node_filters/build.py          # write both copies + fixtures
    python3 graph_db/node_filters/build.py --check  # fail on drift or a bad catalog

Fails on: an undeclared property, an unknown normalizer, an overlap naming a
setting the registry does not have or a tab the settings form does not have,
two selectors on one label that can both match a node, an example that is not
a valid rule, and a finding source that is in no kind and not listed as
deliberately unfiltered.

Runs on a host without the neo4j driver: `graph_db/__init__.py` imports it, so
when the real package cannot be imported a bare namespace stands in for it and
only the stdlib-only modules below are loaded.
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
import types
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
YAML_SRC = HERE / "catalog.yaml"
FIXTURES = HERE / "fixtures"
OUT_ENGINE = HERE / "catalog.json"
WEBAPP_DIR = REPO / "webapp" / "src" / "lib" / "nodeFilters"
OUT_WEBAPP = WEBAPP_DIR / "catalog.json"
OUT_WEBAPP_FIXTURES = WEBAPP_DIR / "fixtures"

RECON_SOURCES = REPO / "recon" / "helpers" / "finding_sources.py"
SCHEMA_PY = REPO / "graph_db" / "schema.py"
REGISTRY = REPO / "recon_settings" / "registry.json"
PROJECT_FORM = REPO / "webapp" / "src" / "components" / "projects" / "ProjectForm" / "ProjectForm.tsx"

GENERATED_NOTE = "Generated by graph_db/node_filters/build.py from catalog.yaml. Do not edit."


def _ensure_graph_db():
    if "graph_db" in sys.modules:
        return
    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))
    try:
        import graph_db  # noqa: F401
    except Exception:
        pkg = types.ModuleType("graph_db")
        pkg.__path__ = [str(REPO / "graph_db")]
        sys.modules["graph_db"] = pkg


_ensure_graph_db()

from graph_db.node_filters import catalog as C  # noqa: E402
from graph_db.node_filters import model as M  # noqa: E402
from graph_db.node_filters.normalize import NORMALIZERS  # noqa: E402
from graph_db.schema_catalog import label_properties  # noqa: E402
from graph_db.schema_keys import KEY_CONSTRAINTS  # noqa: E402


def key_for_label(label: str):
    for entry in KEY_CONSTRAINTS:
        if entry["label"] == label:
            keys = [k for k in entry["key_properties"] if k not in ("user_id", "project_id")]
            return keys[0] if keys else None
    return None


def _tuple_assignment(path: Path, name: str):
    """A module-level `NAME = (...)` read without importing the module."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == name for t in node.targets):
            return tuple(ast.literal_eval(node.value))
    raise SystemExit(f"build.py: {name} not found in {path}")


def known_sources():
    """Every finding source the pipeline or another scanner stamps."""
    return set(_tuple_assignment(RECON_SOURCES, "RECON_FINDING_SOURCES")) | set(
        _tuple_assignment(SCHEMA_PY, "NON_RECON_SOURCES"))


def registry_keys():
    if not REGISTRY.exists():
        return None
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    return set(data.get("fields") or {}) | set(data.get("runtime_only") or {})


def tab_ids():
    if not PROJECT_FORM.exists():
        return None
    src = PROJECT_FORM.read_text(encoding="utf-8")
    block = re.search(r"const TAB_GROUPS = \[(.*?)\] as const", src, re.S)
    return set(re.findall(r"\{ id: '(\w+)'", block.group(1))) if block else None


def build():
    import yaml

    raw = yaml.safe_load(YAML_SRC.read_text(encoding="utf-8"))
    built = C.expand(raw, key_for_label, M.OPERATORS, M.LIMITS)

    def parse_rule(kind_id, rule):
        cfg = M.parse({"version": 1, "kinds": {kind_id: {"enabled": True, "rules": [rule]}}},
                      "denylist", built)
        errors = cfg.errors + [e for k in cfg.kinds.values() for e in k.errors]
        return errors[0] if errors else None

    normalizers = {name: inputs for name, (_fn, inputs) in NORMALIZERS.items()}
    problems = C.check(
        built, lambda label: set(label_properties(label)), normalizers,
        registry_keys=registry_keys(), tab_ids=tab_ids(),
        known_sources=known_sources(), parse_rule=parse_rule,
    )
    return {"_generated": GENERATED_NOTE, **built}, problems


def render(data) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def fixture_files():
    return sorted(p for p in FIXTURES.glob("*.json")) if FIXTURES.exists() else []


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args(argv)

    data, problems = build()
    if problems:
        for p in problems:
            print(f"[node-filters] {p}", file=sys.stderr)
        return 1
    text = render(data)

    targets = [(OUT_ENGINE, text)]
    if WEBAPP_DIR.parent.exists():
        targets.append((OUT_WEBAPP, text))
        for fixture in fixture_files():
            targets.append((OUT_WEBAPP_FIXTURES / fixture.name, fixture.read_text(encoding="utf-8")))

    if args.check:
        drift = [str(p.relative_to(REPO)) for p, body in targets
                 if not p.exists() or p.read_text(encoding="utf-8") != body]
        if WEBAPP_DIR.parent.exists() and OUT_WEBAPP_FIXTURES.exists():
            wanted = {f.name for f in fixture_files()}
            drift += [str(p.relative_to(REPO)) for p in OUT_WEBAPP_FIXTURES.glob("*.json")
                      if p.name not in wanted]
        if drift:
            print("[node-filters] out of date, run graph_db/node_filters/build.py: "
                  + ", ".join(drift), file=sys.stderr)
            return 1
        print(f"[node-filters] catalog OK: {len(data['kinds'])} kinds")
        return 0

    for path, body in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
    if OUT_WEBAPP_FIXTURES.exists():
        wanted = {f.name for f in fixture_files()}
        for stale in OUT_WEBAPP_FIXTURES.glob("*.json"):
            if stale.name not in wanted:
                stale.unlink()
    print(f"[node-filters] wrote {len(targets)} file(s), {len(data['kinds'])} kinds")
    return 0


if __name__ == "__main__":
    sys.exit(main())
