"""The node-filter catalog: build it from catalog.yaml, check it, load it.

`catalog.json` is what runs. It is generated by build.py from catalog.yaml and
read here at runtime, and a copy is written into the webapp so the editor
offers the same kinds, fields and operators the engine accepts.

Everything a kind declares ends up in Cypher as a label or a property name,
since neither can be a parameter. So the catalog is checked twice, by build.py
in the gate and again here at load: every identifier must match
`^[A-Za-z_][A-Za-z0-9_]*$` and be a property the schema declares for that label.
A failure raises `CatalogError`, and a caller that cannot load the catalog
filters nothing.
"""
from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

CATALOG_JSON = Path(__file__).with_name("catalog.json")

#: Phases whose kinds the engine filters today.
ENABLED_PHASES = (1,)

#: Labels the engine may mute. Mirrors MUTEABLE_LABELS in the triage mixin,
#: which also only matches these; anything else is not honoured by the readers.
MUTEABLE = (
    "Vulnerability", "JsReconFinding", "Secret", "MultiscannerFinding",
    "GithubSecret", "GithubSensitiveFile", "MalPackageFinding", "ExploitGvm",
)

#: Properties every finding carries that the schema documents once, in the
#: shared section, rather than per label.
SYSTEM_PROPS = frozenset({
    "id", "user_id", "project_id", "updated_at", "source",
})

SELECT_OPS = ("eq", "in", "not_eq")


class CatalogError(Exception):
    """The catalog is unusable. Nothing is filtered."""


def expand(raw: dict, key_for_label, operators: dict, limits: dict) -> dict:
    """The built catalog: commons merged into kinds, keys resolved, operators embedded."""
    commons = raw.get("common") or {}
    kinds = {}
    for kind_id, entry in (raw.get("kinds") or {}).items():
        fields = {}
        common = entry.get("common")
        if common:
            if common not in commons:
                raise CatalogError(f"{kind_id}: unknown common block {common!r}")
            fields.update({k: dict(v) for k, v in commons[common].items()})
        fields.update({k: dict(v) for k, v in (entry.get("fields") or {}).items()})
        label = entry.get("graph_label")
        kinds[kind_id] = {
            "id": kind_id,
            "group": entry.get("group"),
            "label": entry.get("label", kind_id),
            "graph_label": label,
            "key": key_for_label(label),
            "select": list(entry.get("select") or []),
            "sources": list(entry.get("sources") or []),
            "behaviour": entry.get("behaviour", "finding"),
            "phase": entry.get("phase", 1),
            "fields": fields,
            "overlaps": list(entry.get("overlaps") or []),
            "examples": list(entry.get("examples") or []),
            "notes": [str(n).strip() for n in (entry.get("notes") or [])],
        }
    return {
        "version": raw.get("version", 1),
        "enabled_phases": list(ENABLED_PHASES),
        "ordinals": raw.get("ordinals") or {},
        "groups": raw.get("groups") or [],
        "operators": {t: list(ops) for t, ops in operators.items()},
        "limits": dict(limits),
        "kinds": kinds,
        "unfiltered_sources": raw.get("unfiltered_sources") or {},
        "asset_sources": raw.get("asset_sources") or {},
        "locked": raw.get("locked") or [],
        "planned": raw.get("planned") or [],
    }


def _allowed(item: dict):
    """A selector item as (values, complement): the set it admits, or the set it excludes."""
    if "eq" in item:
        return {str(item["eq"])}, False
    if "in" in item:
        return {str(v) for v in item["in"]}, False
    return {str(item["not_eq"])}, True


def selectors_disjoint(a: list, b: list) -> bool:
    """True when no node can satisfy both selectors.

    Only provable disjointness counts: two kinds on one label must constrain the
    same property to sets that cannot meet. `eq` and `in` never admit a missing
    property, `not_eq` does.
    """
    by_prop_a = {i["prop"]: _allowed(i) for i in a}
    for item in b:
        other = by_prop_a.get(item["prop"])
        if other is None:
            continue
        mine = _allowed(item)
        (sa, ca), (sb, cb) = other, mine
        if not ca and not cb and not (sa & sb):
            return True
        if not ca and cb and sa <= sb:
            return True
        if ca and not cb and sb <= sa:
            return True
    return False


def check(cat: dict, declared_props, normalizers: dict, *, registry_keys=None,
          tab_ids=None, known_sources=None, parse_rule=None) -> list:
    """Every problem with a built catalog, as strings. Empty means usable.

    `declared_props(label)` returns the property names the schema declares for
    that label. The optional arguments enable the build-time checks that need
    files outside graph_db (the settings registry, the settings tabs, the
    pipeline's source list).
    """
    errors = []
    ordinals = cat.get("ordinals") or {}
    operators = cat.get("operators") or {}
    by_label: dict = {}

    for kind_id, kind in (cat.get("kinds") or {}).items():
        where = f"kind {kind_id}"
        label = kind.get("graph_label")
        if not isinstance(label, str) or not IDENT.match(label):
            errors.append(f"{where}: graph_label {label!r} is not an identifier")
            continue
        if kind.get("behaviour") == "finding" and label not in MUTEABLE:
            errors.append(f"{where}: {label} cannot be muted")
        key = kind.get("key")
        if not isinstance(key, str) or not IDENT.match(key):
            errors.append(f"{where}: {label} has no usable key property")
        declared = set(declared_props(label)) | SYSTEM_PROPS

        def need(prop, what):
            if not isinstance(prop, str) or not IDENT.match(prop):
                errors.append(f"{where}: {what} {prop!r} is not an identifier")
            elif prop not in declared:
                errors.append(f"{where}: {what} {prop!r} is not a declared {label} property "
                              f"(graph_db/schema_sections.md)")

        for item in kind.get("select") or []:
            ops = [op for op in SELECT_OPS if op in item]
            if len(ops) != 1 or set(item) - {"prop", *SELECT_OPS}:
                errors.append(f"{where}: a selector item is one of {SELECT_OPS} on one prop")
                continue
            need(item.get("prop"), "selector prop")
            values = item[ops[0]]
            values = values if isinstance(values, list) else [values]
            if not values or not all(isinstance(v, str) and v for v in values):
                errors.append(f"{where}: selector values must be non-empty strings")

        sel_sources = [i for i in kind.get("select") or [] if i.get("prop") == "source" and "in" in i]
        if sel_sources and set(sel_sources[0]["in"]) != set(kind.get("sources") or []):
            errors.append(f"{where}: `sources` must equal the source selector")

        fields = kind.get("fields") or {}
        if not fields:
            errors.append(f"{where}: no fields")
        for name, fdef in fields.items():
            fw = f"field {name}"
            if not IDENT.match(name):
                errors.append(f"{where}: {fw} is not an identifier")
            ftype = fdef.get("type")
            if ftype not in operators:
                errors.append(f"{where}: {fw} has unknown type {ftype!r}")
                continue
            if ftype == "ordinal" and fdef.get("scale") not in ordinals:
                errors.append(f"{where}: {fw} names unknown scale {fdef.get('scale')!r}")
            normalizer = fdef.get("normalizer")
            if normalizer:
                if normalizer not in normalizers:
                    errors.append(f"{where}: {fw} uses unknown normalizer {normalizer!r}")
                    continue
                inputs = normalizers[normalizer]
                if inputs is None:
                    need(fdef.get("from"), f"{fw} input")
                else:
                    for prop in inputs:
                        need(prop, f"{fw} normalizer input")
            else:
                need(fdef.get("prop"), f"{fw} prop")

        for i, example in enumerate(kind.get("examples") or []):
            if parse_rule is not None:
                problem = parse_rule(kind_id, {"id": f"example{i:02d}", "enabled": True, **example})
                if problem:
                    errors.append(f"{where}: example {i + 1}: {problem}")

        for overlap in kind.get("overlaps") or []:
            if registry_keys is not None and overlap.get("setting") not in registry_keys:
                errors.append(f"{where}: overlap setting {overlap.get('setting')!r} is not a registry key")
            if tab_ids is not None and overlap.get("tab") not in tab_ids:
                errors.append(f"{where}: overlap tab {overlap.get('tab')!r} is not a settings tab")

        for other_id, other in by_label.get(label, []):
            if not selectors_disjoint(kind.get("select") or [], other.get("select") or []):
                errors.append(f"{where}: its selector overlaps {other_id} on {label}")
        by_label.setdefault(label, []).append((kind_id, kind))

    if known_sources is not None:
        claimed = set()
        for kind in (cat.get("kinds") or {}).values():
            claimed.update(kind.get("sources") or [])
        claimed |= set(cat.get("unfiltered_sources") or {})
        claimed |= set(cat.get("asset_sources") or {})
        for source in sorted(set(known_sources) - claimed):
            errors.append(f"source {source!r} is in no kind and not listed under "
                          "unfiltered_sources or asset_sources, with a reason")
    for source, reason in {**(cat.get("unfiltered_sources") or {}),
                           **(cat.get("asset_sources") or {})}.items():
        if not str(reason or "").strip():
            errors.append(f"source {source!r} is listed without a reason")
    # An unquoted comma inside a YAML flow mapping ends the reason there and
    # turns the rest into stray null-valued keys, so the Locked panel shows a
    # truncated sentence without any parse error.
    for entry in cat.get("locked") or []:
        if set(entry) != {"label", "reason"} or not str(entry.get("reason") or "").strip():
            errors.append(f"locked entry {entry.get('label')!r} must be exactly a label and a "
                          "reason; quote a reason that contains a comma")
    return errors


class Catalog:
    """A loaded, checked catalog."""

    def __init__(self, data: dict):
        self.data = data
        self.kinds = data["kinds"]
        self.ordinals = data.get("ordinals") or {}

    def kind(self, kind_id: str) -> dict:
        return self.kinds[kind_id]

    def kinds_for_enabled_phases(self) -> list:
        phases = set(self.data.get("enabled_phases") or ENABLED_PHASES)
        return [k for k, v in self.kinds.items() if v.get("phase") in phases]


def _declared_props():
    from graph_db.schema_catalog import label_properties
    return lambda label: set(label_properties(label))


@lru_cache(maxsize=4)
def load_catalog(path: str | None = None) -> Catalog:
    """The runtime catalog, checked. Raises CatalogError; a caller filters nothing then."""
    from .normalize import NORMALIZERS
    target = Path(path) if path else CATALOG_JSON
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise CatalogError(f"cannot read {target.name}: {e}") from e
    normalizers = {name: inputs for name, (_fn, inputs) in NORMALIZERS.items()}
    problems = check(data, _declared_props(), normalizers)
    if problems:
        raise CatalogError("; ".join(problems[:5]))
    return Catalog(data)
