/**
 * The recon-settings allowlist for the inbound MCP server.
 *
 * `PUT /api/projects/[id]` spreads its body straight into `prisma.project.update`,
 * and the Project model carries over 700 scalar columns. Anything that reaches
 * that call is written. Describing exclusions in prose is therefore not a
 * control, and a DENYLIST is the wrong shape: a new Prisma column would default
 * to *permitted*, which is the wrong direction to fail.
 *
 * The attack this prevents, concretely:
 *
 *     update_recon_settings({ targetDomain: "victim.com",
 *                             targetGuardrailEnabled: false })
 *     start_recon()
 *
 * which turns a "rescan my own projects" credential into an attack-launching
 * credential aimed at an arbitrary third party, breaching the platform ->
 * targets boundary that is the product's core legal control.
 *
 * Three layers, all fail-closed:
 *
 *  1. ALLOWLIST - a positive, frozen set. Only genuine recon TUNING: per-tool
 *     enable flags, rate limits, thread and worker counts, timeouts,
 *     concurrency, retries, depth and max-* caps, severity / status-code lists,
 *     and the scanModules set.
 *  2. VALIDATION - every numeric carries an explicit min and max mirroring the
 *     corresponding ProjectForm input; a field with no UI bound is deliberately
 *     NOT allowlisted in v1 (reason: "unbounded").
 *  3. CLASSIFICATION - every Project scalar column appears in ALLOW or DENY
 *     below with a reason. A new Prisma field is in neither, so the coverage
 *     test FAILS until someone classifies it. That is the control that survives
 *     contact with a codebase which adds recon fields weekly, and the staleness
 *     it causes is the correct fail-closed cost, not a bug.
 *
 * Unknown keys reject the WHOLE call naming the offending key; they are never
 * silently stripped, or a caller believes a setting was applied when it was not.
 */

export type DenyReason =
  | 'agent'
  | 'attack'
  | 'egress'
  | 'escalation'
  | 'headers'
  | 'identity'
  | 'image'
  | 'internal'
  | 'intrusive'
  | 'llm'
  | 'not-tuning'
  | 'othertarget'
  | 'roe'
  | 'scope'
  | 'secret'
  | 'unbounded'
  | 'wordlist'

/** Why each denied class is denied, for the error message and the docs. */
export const DENY_REASON_DOC: Readonly<Record<DenyReason, string>> = Object.freeze({
  'agent': 'agent / fireteam behaviour, out of scope for a recon credential',
  'attack': 'exploitation technique, out of scope for a recon credential',
  'egress': 'reaches a collector or fetches from outside the engagement',
  'escalation': 'would let a token grant itself a capability it was not issued',
  'headers': 'arbitrary headers sent to the target, including Host and credentials',
  'identity': 'row identity / audit columns',
  'image': 'decides what container gets spawned',
  'internal': 'internal state, not a setting',
  'intrusive': 'raises the aggression of traffic aimed at a live third party',
  'llm': 'model choice or billable LLM spend',
  'not-tuning': 'not a recon tuning knob',
  'othertarget': 'steers another scan at someone else assets',
  'roe': 'the encoded engagement agreement',
  'scope': 'engagement scope - changing it points the platform at a new victim',
  'secret': 'a credential',
  'unbounded': 'genuine tuning, but no ProjectForm bound to mirror - not in v1',
  'wordlist': 'attacker-supplied file or pattern that reaches a scan container',
})

export type AllowedSetting =
  | { kind: 'boolean' }
  | { kind: 'number'; min: number; max: number }
  | { kind: 'string-list' }
  | { kind: 'enum-list' }

/**
 * The only Project columns an MCP caller may write. Frozen: this set is a
 * security boundary, not a default.
 */
export const RECON_SETTINGS_ALLOWLIST: Readonly<Record<string, AllowedSetting>> = Object.freeze({
  amassEnabled: { kind: 'boolean' },
  amassMaxResults: { kind: 'number', min: 1, max: 50000 },
  amassTimeout: { kind: 'number', min: 1, max: 120 },
  arjunChunkSize: { kind: 'number', min: 10, max: 5000 },
  arjunEnabled: { kind: 'boolean' },
  arjunMaxEndpoints: { kind: 'number', min: 1, max: 50000 },
  arjunThreads: { kind: 'number', min: 1, max: 20 },
  baddnsEnabled: { kind: 'boolean' },
  bannerGrabEnabled: { kind: 'boolean' },
  bannerGrabMaxLength: { kind: 'number', min: 100, max: 5000 },
  censysEnabled: { kind: 'boolean' },
  censysWorkers: { kind: 'number', min: 1, max: 20 },
  criminalIpEnabled: { kind: 'boolean' },
  criminalIpWorkers: { kind: 'number', min: 1, max: 20 },
  crtshEnabled: { kind: 'boolean' },
  crtshMaxResults: { kind: 'number', min: 1, max: 50000 },
  cveLookupEnabled: { kind: 'boolean' },
  dnsEnabled: { kind: 'boolean' },
  dnsMaxRetries: { kind: 'number', min: 1, max: 10 },
  dnsMaxWorkers: { kind: 'number', min: 1, max: 200 },
  ffufEnabled: { kind: 'boolean' },
  ffufRecursionDepth: { kind: 'number', min: 1, max: 5 },
  ffufThreads: { kind: 'number', min: 1, max: 200 },
  fofaEnabled: { kind: 'boolean' },
  fofaMaxResults: { kind: 'number', min: 1, max: 10000 },
  fofaWorkers: { kind: 'number', min: 1, max: 20 },
  gauEnabled: { kind: 'boolean' },
  gauThreads: { kind: 'number', min: 1, max: 20 },
  gauVerifyThreads: { kind: 'number', min: 1, max: 100 },
  gauWorkers: { kind: 'number', min: 1, max: 20 },
  githubMaxCommits: { kind: 'number', min: 1, max: 1000 },
  graphqlConcurrency: { kind: 'number', min: 1, max: 20 },
  graphqlCopEnabled: { kind: 'boolean' },
  graphqlCopTimeout: { kind: 'number', min: 10, max: 600 },
  graphqlDepthLimit: { kind: 'number', min: 1, max: 50 },
  graphqlRateLimit: { kind: 'number', min: 0, max: 100 },
  graphqlSecurityEnabled: { kind: 'boolean' },
  graphqlTimeout: { kind: 'number', min: 1, max: 600 },
  hackerTargetEnabled: { kind: 'boolean' },
  hackerTargetMaxResults: { kind: 'number', min: 1, max: 50000 },
  hakrawlerDepth: { kind: 'number', min: 1, max: 10 },
  hakrawlerEnabled: { kind: 'boolean' },
  hakrawlerThreads: { kind: 'number', min: 1, max: 20 },
  httpxEnabled: { kind: 'boolean' },
  httpxFilterCodes: { kind: 'string-list' },
  httpxMatchCodes: { kind: 'string-list' },
  httpxMaxRedirects: { kind: 'number', min: 1, max: 50 },
  httpxRetries: { kind: 'number', min: 0, max: 10 },
  httpxThreads: { kind: 'number', min: 1, max: 200 },
  jsReconConcurrency: { kind: 'number', min: 1, max: 30 },
  jsReconEnabled: { kind: 'boolean' },
  jsReconEndpointConcurrency: { kind: 'number', min: 1, max: 20 },
  jsReconValidationTimeout: { kind: 'number', min: 1, max: 30 },
  jsluiceConcurrency: { kind: 'number', min: 1, max: 20 },
  jsluiceEnabled: { kind: 'boolean' },
  jsluiceVerifyRateLimit: { kind: 'number', min: 1, max: 1000 },
  jsluiceVerifyThreads: { kind: 'number', min: 1, max: 500 },
  jsluiceVerifyTimeout: { kind: 'number', min: 1, max: 60 },
  katanaConcurrency: { kind: 'number', min: 1, max: 50 },
  katanaDepth: { kind: 'number', min: 1, max: 10 },
  katanaEnabled: { kind: 'boolean' },
  kiterunnerEnabled: { kind: 'boolean' },
  knockpyReconEnabled: { kind: 'boolean' },
  knockpyReconMaxResults: { kind: 'number', min: 1, max: 50000 },
  masscanEnabled: { kind: 'boolean' },
  masscanRetries: { kind: 'number', min: 0, max: 10 },
  mitreEnabled: { kind: 'boolean' },
  naabuEnabled: { kind: 'boolean' },
  naabuRetries: { kind: 'number', min: 0, max: 10 },
  naabuThreads: { kind: 'number', min: 1, max: 100 },
  netlasEnabled: { kind: 'boolean' },
  netlasWorkers: { kind: 'number', min: 1, max: 20 },
  nmapEnabled: { kind: 'boolean' },
  nucleiEnabled: { kind: 'boolean' },
  nucleiMaxRedirects: { kind: 'number', min: 0, max: 50 },
  nucleiRetries: { kind: 'number', min: 0, max: 10 },
  nucleiSeverity: { kind: 'string-list' },
  nucleiTakeoversEnabled: { kind: 'boolean' },
  osintEnrichmentEnabled: { kind: 'boolean' },
  otxEnabled: { kind: 'boolean' },
  otxWorkers: { kind: 'number', min: 1, max: 20 },
  paramspiderEnabled: { kind: 'boolean' },
  paramspiderWorkers: { kind: 'number', min: 1, max: 10 },
  purednsEnabled: { kind: 'boolean' },
  purednsThreads: { kind: 'number', min: 0, max: 1000 },
  scanModules: { kind: 'enum-list' },
  securityCheckEnabled: { kind: 'boolean' },
  securityCheckMaxWorkers: { kind: 'number', min: 1, max: 50 },
  shodanEnabled: { kind: 'boolean' },
  shodanWorkers: { kind: 'number', min: 1, max: 20 },
  subdomainDiscoveryEnabled: { kind: 'boolean' },
  subdomainTakeoverEnabled: { kind: 'boolean' },
  subfinderEnabled: { kind: 'boolean' },
  subfinderMaxResults: { kind: 'number', min: 1, max: 50000 },
  subjackEnabled: { kind: 'boolean' },
  subjackThreads: { kind: 'number', min: 1, max: 100 },
  supplyChainDeepAnalysisEnabled: { kind: 'boolean' },
  supplyChainOrgDeepAnalysisEnabled: { kind: 'boolean' },
  supplyChainReconDeepAnalysisEnabled: { kind: 'boolean' },
  supplyChainReconEnabled: { kind: 'boolean' },
  supplyChainTyposquatEnabled: { kind: 'boolean' },
  takeoverCertValidationEnabled: { kind: 'boolean' },
  takeoverRateLimit: { kind: 'number', min: 1, max: 500 },
  takeoverSeverity: { kind: 'string-list' },
  tlsxConcurrency: { kind: 'number', min: 1, max: 300 },
  tlsxEnabled: { kind: 'boolean' },
  tlsxMaxTargets: { kind: 'number', min: 1, max: 100000 },
  tlsxTimeout: { kind: 'number', min: 1, max: 60 },
  trufflehogEnabled: { kind: 'boolean' },
  uncoverEnabled: { kind: 'boolean' },
  uncoverMaxResults: { kind: 'number', min: 1, max: 50000 },
  urlscanEnabled: { kind: 'boolean' },
  urlscanMaxResults: { kind: 'number', min: 1, max: 50000 },
  vhostSniBaselineSizeTolerance: { kind: 'number', min: 0, max: 10000 },
  vhostSniConcurrency: { kind: 'number', min: 1, max: 100 },
  vhostSniEnabled: { kind: 'boolean' },
  vhostSniTimeout: { kind: 'number', min: 1, max: 30 },
  virusTotalEnabled: { kind: 'boolean' },
  virusTotalWorkers: { kind: 'number', min: 1, max: 10 },
  wappalyzerEnabled: { kind: 'boolean' },
  whoisEnabled: { kind: 'boolean' },
  whoisMaxRetries: { kind: 'number', min: 1, max: 20 },
  zapAjaxSpiderEnabled: { kind: 'boolean' },
  zoomEyeEnabled: { kind: 'boolean' },
  zoomEyeMaxResults: { kind: 'number', min: 1, max: 10000 },
  zoomEyeWorkers: { kind: 'number', min: 1, max: 20 },
})

/**
 * Every Project scalar column that an MCP caller may NOT write, with the class
 * it falls in. Kept exhaustive so a new column is visibly unclassified.
 */
export const RECON_SETTINGS_DENYLIST: Readonly<Record<string, DenyReason>> = Object.freeze({
  activationStartedAt: 'internal',
  activationState: 'internal',
  activationVersionId: 'not-tuning',
  agentActivatePostExplPhase: 'agent',
  agentBindPortOnTarget: 'agent',
  agentBruteForceMaxWordlistAttempts: 'wordlist',
  agentBruteforceSpeed: 'agent',
  agentChiselTunnelEnabled: 'agent',
  agentCreateGraphImageOnInit: 'agent',
  agentCypherMaxRetries: 'agent',
  agentExecutionTraceMemorySteps: 'agent',
  agentExplSystemPrompt: 'llm',
  agentGuardrailEnabled: 'agent',
  agentInformationalSystemPrompt: 'llm',
  agentKaliInstallAllowedPackages: 'agent',
  agentKaliInstallEnabled: 'agent',
  agentKaliInstallForbiddenPackages: 'agent',
  agentLatsBranching: 'agent',
  agentLatsEnabled: 'agent',
  agentLatsMaxDepth: 'agent',
  agentLatsMaxRollouts: 'agent',
  agentLatsMaxTreeNodes: 'agent',
  agentLatsMinHypotheses: 'agent',
  agentLatsPhaseExploitation: 'agent',
  agentLatsPhasePostExpl: 'agent',
  agentLatsPruneFloor: 'agent',
  agentLatsShadowMode: 'agent',
  agentLatsUctC: 'agent',
  agentLhost: 'agent',
  agentLlmParseMaxRetries: 'llm',
  agentLogBackupCount: 'agent',
  agentLogMaxMb: 'agent',
  agentLport: 'agent',
  agentMaxIterations: 'agent',
  agentNgrokTunnelEnabled: 'agent',
  agentOpenaiModel: 'llm',
  agentPayloadUseHttps: 'wordlist',
  agentPlanMaxParallelTools: 'agent',
  agentPostExplPhaseType: 'agent',
  agentPostExplSystemPrompt: 'llm',
  agentRequireApprovalForExploitation: 'agent',
  agentRequireApprovalForPostExploitation: 'agent',
  agentRequireToolConfirmation: 'agent',
  agentToolOutputMaxChars: 'agent',
  agentToolPhaseMap: 'agent',
  aiInPipeline: 'llm',
  aiPipelineModel: 'llm',
  aiSurfaceReconCacheEnabled: 'llm',
  aiSurfaceReconChatShapeProbeEnabled: 'llm',
  aiSurfaceReconEnabled: 'llm',
  aiSurfaceReconJuliusProbePackEnabled: 'llm',
  aiSurfaceReconLatencyBaselineEnabled: 'llm',
  aiSurfaceReconMaxWorkers: 'llm',
  aiSurfaceReconMcpHandshakeEnabled: 'llm',
  aiSurfaceReconMcpListToolsEnabled: 'llm',
  aiSurfaceReconMcpYaraEnabled: 'llm',
  aiSurfaceReconModelListEnabled: 'llm',
  aiSurfaceReconOpenapiDiscoveryEnabled: 'llm',
  aiSurfaceReconProbePackVersion: 'llm',
  aiSurfaceReconTimeout: 'llm',
  aiSurfaceReconUserAgent: 'llm',
  aiSurfaceReconVectorDbReadEnabled: 'llm',
  amassActive: 'intrusive',
  amassBrute: 'intrusive',
  amassBruteWordlists: 'wordlist',
  amassDockerImage: 'image',
  arjunCustomHeaders: 'headers',
  arjunDisableRedirects: 'not-tuning',
  arjunMethods: 'not-tuning',
  arjunPassive: 'not-tuning',
  arjunRateLimit: 'unbounded',
  arjunScanTimeout: 'unbounded',
  arjunStable: 'not-tuning',
  arjunTimeout: 'unbounded',
  attackSkillConfig: 'agent',
  baddnsDockerImage: 'image',
  baddnsModules: 'not-tuning',
  baddnsNameservers: 'egress',
  baddnsRunTimeout: 'unbounded',
  bannerGrabThreads: 'unbounded',
  bannerGrabTimeout: 'unbounded',
  captureProxyEnabled: 'intrusive',
  createdAt: 'identity',
  createdById: 'identity',
  cveLookupMaxCves: 'not-tuning',
  cveLookupMinCvss: 'not-tuning',
  cveLookupSource: 'not-tuning',
  cypherfixBranchPrefix: 'agent',
  cypherfixDefaultBranch: 'agent',
  cypherfixDefaultRepo: 'agent',
  cypherfixGithubToken: 'secret',
  cypherfixLlmModel: 'llm',
  cypherfixRequireApproval: 'agent',
  description: 'identity',
  dnsRecordParallelism: 'not-tuning',
  domainBatchGroups: 'scope',
  domainBatchHosts: 'scope',
  domainBatchMode: 'scope',
  domainReconAiNsHintEnabled: 'llm',
  domainReconAiTxtHintEnabled: 'llm',
  dosAssessmentOnly: 'intrusive',
  dosConcurrentConnections: 'intrusive',
  dosMaxAttempts: 'intrusive',
  dosMaxDuration: 'intrusive',
  ffufAiExtensions: 'llm',
  ffufAutoCalibrate: 'not-tuning',
  ffufCustomHeaders: 'headers',
  ffufExtensions: 'not-tuning',
  ffufFilterCodes: 'not-tuning',
  ffufFilterSize: 'not-tuning',
  ffufFollowRedirects: 'not-tuning',
  ffufMatchCodes: 'not-tuning',
  ffufMaxTime: 'not-tuning',
  ffufParallelism: 'not-tuning',
  ffufRate: 'unbounded',
  ffufRecursion: 'not-tuning',
  ffufSmartFuzz: 'not-tuning',
  ffufTimeout: 'unbounded',
  ffufWordlist: 'wordlist',
  fireteamAllowedPhases: 'agent',
  fireteamConfirmationTimeoutSec: 'agent',
  fireteamEnabled: 'agent',
  fireteamMaxConcurrent: 'agent',
  fireteamMaxMembers: 'agent',
  fireteamMemberMaxIterations: 'agent',
  fireteamPropensity: 'agent',
  fireteamTimeoutSec: 'agent',
  gauBlacklistExtensions: 'not-tuning',
  gauDetectMethods: 'not-tuning',
  gauDockerImage: 'image',
  gauFilterDeadEndpoints: 'not-tuning',
  gauMaxUrls: 'unbounded',
  gauMethodDetectRateLimit: 'unbounded',
  gauMethodDetectThreads: 'unbounded',
  gauMethodDetectTimeout: 'unbounded',
  gauProviders: 'not-tuning',
  gauTimeout: 'unbounded',
  gauVerbose: 'not-tuning',
  gauVerifyAcceptStatus: 'not-tuning',
  gauVerifyDockerImage: 'image',
  gauVerifyRateLimit: 'unbounded',
  gauVerifyTimeout: 'unbounded',
  gauVerifyUrls: 'not-tuning',
  gauYearRange: 'not-tuning',
  githubOutputJson: 'not-tuning',
  githubScanCommits: 'not-tuning',
  githubScanGists: 'not-tuning',
  githubScanMembers: 'not-tuning',
  githubTargetOrg: 'othertarget',
  githubTargetRepos: 'othertarget',
  graphqlAuthHeader: 'secret',
  graphqlAuthType: 'not-tuning',
  graphqlAuthValue: 'secret',
  graphqlCopDebug: 'not-tuning',
  graphqlCopDockerImage: 'image',
  graphqlCopForceScan: 'not-tuning',
  graphqlCopTestAliasOverloading: 'not-tuning',
  graphqlCopTestBatchQuery: 'not-tuning',
  graphqlCopTestCircularIntrospection: 'not-tuning',
  graphqlCopTestDirectiveOverloading: 'not-tuning',
  graphqlCopTestFieldSuggestions: 'not-tuning',
  graphqlCopTestGetMethod: 'not-tuning',
  graphqlCopTestGetMutation: 'not-tuning',
  graphqlCopTestGraphiql: 'not-tuning',
  graphqlCopTestIntrospection: 'not-tuning',
  graphqlCopTestPostCsrf: 'not-tuning',
  graphqlCopTestTraceMode: 'not-tuning',
  graphqlCopTestUnhandledError: 'not-tuning',
  graphqlEndpoints: 'egress',
  graphqlIntrospectionTest: 'not-tuning',
  graphqlRetryBackoff: 'not-tuning',
  graphqlRetryCount: 'not-tuning',
  graphqlVerifySsl: 'not-tuning',
  gvmCleanupAfterScan: 'not-tuning',
  gvmPollInterval: 'not-tuning',
  gvmPortList: 'not-tuning',
  gvmScanConfig: 'not-tuning',
  gvmScanTargets: 'othertarget',
  gvmTaskTimeout: 'unbounded',
  hakrawlerCustomHeaders: 'headers',
  hakrawlerDockerImage: 'image',
  hakrawlerIncludeSubs: 'not-tuning',
  hakrawlerInsecure: 'not-tuning',
  hakrawlerMaxUrls: 'unbounded',
  hakrawlerParallelism: 'not-tuning',
  hakrawlerTimeout: 'unbounded',
  httpProbeAiFaviconHashEnabled: 'llm',
  httpProbeAiHeaderScanEnabled: 'llm',
  httpProbeAiTitleDetectionEnabled: 'llm',
  httpProbeAiWappalyzerEnabled: 'llm',
  httpxCustomHeaders: 'headers',
  httpxDockerImage: 'image',
  httpxFollowRedirects: 'not-tuning',
  httpxIncludeResponse: 'not-tuning',
  httpxIncludeResponseHeaders: 'not-tuning',
  httpxPaths: 'not-tuning',
  httpxProbeAsn: 'not-tuning',
  httpxProbeCdn: 'not-tuning',
  httpxProbeCname: 'not-tuning',
  httpxProbeContentLength: 'not-tuning',
  httpxProbeContentType: 'not-tuning',
  httpxProbeFavicon: 'not-tuning',
  httpxProbeHash: 'not-tuning',
  httpxProbeIp: 'not-tuning',
  httpxProbeJarm: 'not-tuning',
  httpxProbeLineCount: 'not-tuning',
  httpxProbeResponseTime: 'not-tuning',
  httpxProbeServer: 'not-tuning',
  httpxProbeStatusCode: 'not-tuning',
  httpxProbeTechDetect: 'not-tuning',
  httpxProbeTitle: 'not-tuning',
  httpxProbeTlsGrab: 'not-tuning',
  httpxProbeTlsInfo: 'not-tuning',
  httpxProbeWordCount: 'not-tuning',
  httpxRateLimit: 'unbounded',
  httpxTimeout: 'unbounded',
  hydraConnectionTimeout: 'intrusive',
  hydraEnabled: 'intrusive',
  hydraExtraChecks: 'intrusive',
  hydraMaxWordlistAttempts: 'wordlist',
  hydraStopOnFirstFound: 'intrusive',
  hydraThreads: 'intrusive',
  hydraVerbose: 'intrusive',
  hydraWaitBetweenConnections: 'intrusive',
  id: 'identity',
  ipMode: 'scope',
  jsReconAiSdkDetectionEnabled: 'llm',
  jsReconCustomEndpointKeywords: 'not-tuning',
  jsReconCustomFrameworks: 'not-tuning',
  jsReconCustomPackages: 'not-tuning',
  jsReconCustomPatterns: 'wordlist',
  jsReconCustomSourcemapPaths: 'not-tuning',
  jsReconDependencyCheck: 'not-tuning',
  jsReconDevComments: 'not-tuning',
  jsReconDomSinks: 'not-tuning',
  jsReconEndpointAcceptStatus: 'not-tuning',
  jsReconEndpointCustomHeaders: 'headers',
  jsReconExtractEndpoints: 'not-tuning',
  jsReconFrameworkDetect: 'not-tuning',
  jsReconIncludeArchivedJs: 'not-tuning',
  jsReconIncludeChunks: 'not-tuning',
  jsReconIncludeFrameworkJs: 'not-tuning',
  jsReconMaxFiles: 'not-tuning',
  jsReconMinConfidence: 'not-tuning',
  jsReconRegexPatterns: 'not-tuning',
  jsReconSourceMaps: 'not-tuning',
  jsReconStandaloneCrawlDepth: 'unbounded',
  jsReconStandaloneCrawlScope: 'not-tuning',
  jsReconTimeout: 'unbounded',
  jsReconUploadedFiles: 'wordlist',
  jsReconValidateEndpoints: 'not-tuning',
  jsReconValidateKeys: 'not-tuning',
  jsluiceExcludePatterns: 'not-tuning',
  jsluiceExtractSecrets: 'secret',
  jsluiceExtractUrls: 'not-tuning',
  jsluiceMaxFiles: 'not-tuning',
  jsluiceParallelism: 'not-tuning',
  jsluiceTimeout: 'unbounded',
  jsluiceVerifyAcceptStatus: 'not-tuning',
  jsluiceVerifyDockerImage: 'image',
  jsluiceVerifyUrls: 'not-tuning',
  katanaCustomHeaders: 'headers',
  katanaDockerImage: 'image',
  katanaExcludePatterns: 'not-tuning',
  katanaJsCrawl: 'not-tuning',
  katanaMaxUrls: 'unbounded',
  katanaParallelism: 'not-tuning',
  katanaParamsOnly: 'not-tuning',
  katanaRateLimit: 'unbounded',
  katanaScope: 'not-tuning',
  katanaTimeout: 'unbounded',
  kiterunnerBruteforceMethods: 'not-tuning',
  kiterunnerConnections: 'not-tuning',
  kiterunnerDetectMethods: 'not-tuning',
  kiterunnerHeaders: 'not-tuning',
  kiterunnerIgnoreStatus: 'not-tuning',
  kiterunnerMatchStatus: 'not-tuning',
  kiterunnerMethodDetectRateLimit: 'unbounded',
  kiterunnerMethodDetectThreads: 'unbounded',
  kiterunnerMethodDetectTimeout: 'unbounded',
  kiterunnerMethodDetectionMode: 'not-tuning',
  kiterunnerMinContentLength: 'not-tuning',
  kiterunnerParallelism: 'not-tuning',
  kiterunnerRateLimit: 'unbounded',
  kiterunnerScanTimeout: 'unbounded',
  kiterunnerThreads: 'unbounded',
  kiterunnerTimeout: 'unbounded',
  kiterunnerWordlists: 'wordlist',
  masscanAiPortCatalogEnabled: 'llm',
  masscanBanners: 'not-tuning',
  masscanCustomPorts: 'not-tuning',
  masscanExcludeTargets: 'not-tuning',
  masscanRate: 'unbounded',
  masscanTopPorts: 'not-tuning',
  masscanWait: 'not-tuning',
  mcpKaliExecEnabled: 'escalation',
  mitreAutoUpdateDb: 'not-tuning',
  mitreCacheTtlHours: 'not-tuning',
  mitreEnrichGvm: 'not-tuning',
  mitreEnrichRecon: 'not-tuning',
  mitreIncludeCapec: 'not-tuning',
  mitreIncludeCwe: 'not-tuning',
  naabuCustomPorts: 'not-tuning',
  naabuDisplayCdn: 'not-tuning',
  naabuDockerImage: 'image',
  naabuExcludeCdn: 'not-tuning',
  naabuPassiveMode: 'not-tuning',
  naabuRateLimit: 'unbounded',
  naabuScanType: 'not-tuning',
  naabuSkipHostDiscovery: 'not-tuning',
  naabuTimeout: 'unbounded',
  naabuTopPorts: 'not-tuning',
  naabuVerifyPorts: 'not-tuning',
  name: 'identity',
  nmapAiVersionRegexEnabled: 'llm',
  nmapHostTimeout: 'unbounded',
  nmapParallelism: 'not-tuning',
  nmapScriptScan: 'not-tuning',
  nmapTimeout: 'unbounded',
  nmapTimingTemplate: 'wordlist',
  nmapVersionDetection: 'not-tuning',
  nucleiAiResponseFilter: 'llm',
  nucleiAiTags: 'llm',
  nucleiAutoUpdateTemplates: 'wordlist',
  nucleiBulkSize: 'not-tuning',
  nucleiConcurrency: 'unbounded',
  nucleiCustomTemplates: 'wordlist',
  nucleiDastMode: 'intrusive',
  nucleiDockerImage: 'image',
  nucleiExcludeTags: 'not-tuning',
  nucleiExcludeTemplates: 'wordlist',
  nucleiFollowRedirects: 'not-tuning',
  nucleiHeadless: 'intrusive',
  nucleiInteractsh: 'egress',
  nucleiNewTemplatesOnly: 'wordlist',
  nucleiRateLimit: 'unbounded',
  nucleiScanAllIps: 'not-tuning',
  nucleiSelectedCustomTemplates: 'wordlist',
  nucleiSystemResolvers: 'not-tuning',
  nucleiTags: 'not-tuning',
  nucleiTakeoverRunTimeout: 'unbounded',
  nucleiTemplates: 'wordlist',
  nucleiTimeout: 'unbounded',
  originDiscoveryEnabled: 'egress',
  originDiscoveryKeyless: 'egress',
  originDiscoveryMaxCandidates: 'egress',
  originDiscoveryMaxSearchCalls: 'egress',
  originDiscoveryPassiveDns: 'egress',
  originDiscoveryScanners: 'egress',
  originDiscoveryThreshold: 'egress',
  originDiscoveryTimeout: 'egress',
  originDiscoveryWorkers: 'egress',
  ownershipToken: 'scope',
  ownershipTxtPrefix: 'scope',
  paramspiderPlaceholder: 'not-tuning',
  paramspiderTimeout: 'unbounded',
  pathTraversalArchiveExtractionEnabled: 'attack',
  pathTraversalOobCallbackEnabled: 'egress',
  pathTraversalOobProvider: 'egress',
  pathTraversalPayloadReferenceEnabled: 'wordlist',
  pathTraversalPhpWrappersEnabled: 'attack',
  pathTraversalRequestTimeout: 'attack',
  phishingSmtpConfig: 'intrusive',
  portScanAiPortCatalogEnabled: 'llm',
  purednsDockerImage: 'image',
  purednsRateLimit: 'unbounded',
  purednsSkipValidation: 'not-tuning',
  purednsWildcardBatch: 'not-tuning',
  rceAggressivePayloads: 'wordlist',
  rceDeserializationEnabled: 'attack',
  rceOobCallbackEnabled: 'egress',
  reconPresetId: 'internal',
  resourceEnumAiClassifierEnabled: 'llm',
  resourceEnumAiParamInjectableFlagEnabled: 'llm',
  resourceEnumAiPathClassifierEnabled: 'llm',
  resourceEnumAiRagPathFlagEnabled: 'llm',
  resourceEnumAiToolArgPathEnabled: 'llm',
  roeAllowAccountLockout: 'roe',
  roeAllowDataExfiltration: 'roe',
  roeAllowDos: 'roe',
  roeAllowPhysicalAccess: 'roe',
  roeAllowProductionTesting: 'roe',
  roeAllowSocialEngineering: 'roe',
  roeClientContactEmail: 'roe',
  roeClientContactName: 'roe',
  roeClientContactPhone: 'roe',
  roeClientName: 'roe',
  roeComplianceFrameworks: 'roe',
  roeCriticalFindingNotify: 'roe',
  roeDataRetentionDays: 'roe',
  roeDocumentData: 'roe',
  roeDocumentMimeType: 'roe',
  roeDocumentName: 'roe',
  roeEmergencyContact: 'roe',
  roeEnabled: 'roe',
  roeEngagementEndDate: 'roe',
  roeEngagementStartDate: 'roe',
  roeEngagementType: 'roe',
  roeExcludedHostReasons: 'roe',
  roeExcludedHosts: 'roe',
  roeForbiddenCategories: 'roe',
  roeForbiddenTools: 'roe',
  roeGlobalMaxRps: 'roe',
  roeIncidentProcedure: 'roe',
  roeMaxSeverityPhase: 'roe',
  roeNotes: 'roe',
  roeParsedJson: 'roe',
  roeRawText: 'roe',
  roeRequireDataEncryption: 'roe',
  roeSensitiveDataHandling: 'roe',
  roeStatusUpdateFrequency: 'roe',
  roeThirdPartyProviders: 'roe',
  roeTimeWindowDays: 'roe',
  roeTimeWindowEnabled: 'roe',
  roeTimeWindowEndTime: 'roe',
  roeTimeWindowStartTime: 'roe',
  roeTimeWindowTimezone: 'roe',
  scaIntelCorrelationEnabled: 'othertarget',
  securityCheckAdminPortExposed: 'not-tuning',
  securityCheckBasicAuthNoTls: 'not-tuning',
  securityCheckCacheControlMissing: 'not-tuning',
  securityCheckCspUnsafeInline: 'not-tuning',
  securityCheckDatabaseExposed: 'not-tuning',
  securityCheckDirectIpHttp: 'not-tuning',
  securityCheckDirectIpHttps: 'not-tuning',
  securityCheckDmarcMissing: 'not-tuning',
  securityCheckDnssecMissing: 'not-tuning',
  securityCheckInsecureFormAction: 'not-tuning',
  securityCheckIpApiExposed: 'not-tuning',
  securityCheckKubernetesApiExposed: 'not-tuning',
  securityCheckLoginNoHttps: 'not-tuning',
  securityCheckMissingCoep: 'not-tuning',
  securityCheckMissingCoop: 'not-tuning',
  securityCheckMissingCorp: 'not-tuning',
  securityCheckMissingPermissionsPolicy: 'not-tuning',
  securityCheckMissingReferrerPolicy: 'not-tuning',
  securityCheckNoRateLimiting: 'not-tuning',
  securityCheckRedisNoAuth: 'not-tuning',
  securityCheckSessionNoHttponly: 'not-tuning',
  securityCheckSessionNoSecure: 'not-tuning',
  securityCheckSmtpOpenRelay: 'intrusive',
  securityCheckSpfMissing: 'not-tuning',
  securityCheckTimeout: 'unbounded',
  securityCheckTlsExpired: 'not-tuning',
  securityCheckTlsExpiringSoon: 'not-tuning',
  securityCheckTlsExpiryDays: 'not-tuning',
  securityCheckTlsHostnameMismatch: 'not-tuning',
  securityCheckTlsSelfSigned: 'not-tuning',
  securityCheckTlsWeakCipher: 'not-tuning',
  securityCheckTlsWeakVersion: 'not-tuning',
  securityCheckTlsWildcardOverbroad: 'not-tuning',
  securityCheckWafBypass: 'not-tuning',
  securityCheckZoneTransfer: 'not-tuning',
  shodanDomainDns: 'not-tuning',
  shodanHostLookup: 'not-tuning',
  shodanPassiveCves: 'not-tuning',
  shodanReverseDns: 'not-tuning',
  sqliLevel: 'attack',
  sqliRisk: 'attack',
  sqliTamperScripts: 'wordlist',
  ssrfCloudMetadataEnabled: 'egress',
  ssrfCloudProviders: 'egress',
  ssrfCustomInternalTargets: 'egress',
  ssrfDnsRebindingEnabled: 'egress',
  ssrfGopherEnabled: 'egress',
  ssrfInternalRanges: 'egress',
  ssrfOobCallbackEnabled: 'egress',
  ssrfOobProvider: 'egress',
  ssrfPayloadReferenceEnabled: 'egress',
  ssrfPortScanPorts: 'egress',
  ssrfRequestTimeout: 'egress',
  stealthMode: 'intrusive',
  subdomainList: 'scope',
  subfinderDockerImage: 'image',
  subjackAll: 'not-tuning',
  subjackCheckAr: 'not-tuning',
  subjackCheckMail: 'not-tuning',
  subjackCheckNs: 'not-tuning',
  subjackRunTimeout: 'unbounded',
  subjackSsl: 'not-tuning',
  subjackTimeout: 'unbounded',
  supplyChainEcosystems: 'not-tuning',
  supplyChainInputMode: 'not-tuning',
  supplyChainOrgIncludeArchived: 'not-tuning',
  supplyChainOrgIncludeForks: 'not-tuning',
  supplyChainOrgMaxRepos: 'unbounded',
  supplyChainOrgName: 'othertarget',
  supplyChainOrgRef: 'not-tuning',
  supplyChainReconEcosystems: 'not-tuning',
  supplyChainRepoRef: 'othertarget',
  supplyChainRepoScope: 'othertarget',
  supplyChainRepoUrl: 'othertarget',
  supplyChainSbomFile: 'not-tuning',
  takeoverAiClassifier: 'llm',
  takeoverConfidenceThreshold: 'not-tuning',
  takeoverManualReviewAutoPublish: 'not-tuning',
  targetDomain: 'scope',
  targetGuardrailEnabled: 'scope',
  targetIps: 'scope',
  tlsxCipherConcurrency: 'unbounded',
  tlsxCipherEnum: 'not-tuning',
  tlsxDelay: 'not-tuning',
  tlsxDockerImage: 'image',
  tlsxIncludeHttpPorts: 'not-tuning',
  tlsxInjectHostnames: 'not-tuning',
  tlsxMaxHostnamesPerIp: 'not-tuning',
  tlsxMaxInjectedHostnames: 'not-tuning',
  tlsxProbeJarm: 'not-tuning',
  tlsxRetries: 'unbounded',
  tlsxRevPtrSni: 'not-tuning',
  tlsxRunTimeout: 'unbounded',
  tlsxScanMode: 'not-tuning',
  tlsxVersionEnum: 'not-tuning',
  triageReviewBudget: 'not-tuning',
  trufflehogAllowVerificationOverlap: 'not-tuning',
  trufflehogArchiveMaxDepth: 'unbounded',
  trufflehogArchiveMaxSize: 'not-tuning',
  trufflehogArchiveTimeout: 'not-tuning',
  trufflehogConcurrency: 'unbounded',
  trufflehogDetectorTimeout: 'not-tuning',
  trufflehogDropUnverifiedJwt: 'not-tuning',
  trufflehogExcludeDetectors: 'not-tuning',
  trufflehogFilterEntropy: 'not-tuning',
  trufflehogForceSkipArchives: 'not-tuning',
  trufflehogForceSkipBinaries: 'not-tuning',
  trufflehogIncludeDetectors: 'not-tuning',
  trufflehogMaxDecodeDepth: 'unbounded',
  trufflehogNoVerification: 'not-tuning',
  trufflehogResultTypes: 'not-tuning',
  uncoverDockerImage: 'image',
  updateGraphDb: 'not-tuning',
  updatedAt: 'identity',
  updatedById: 'identity',
  useBruteforceForSubdomains: 'intrusive',
  userId: 'identity',
  verifyDomainOwnership: 'scope',
  vhostSniCustomWordlist: 'wordlist',
  vhostSniInjectDiscovered: 'not-tuning',
  vhostSniMaxCandidatesPerIp: 'not-tuning',
  vhostSniTestL4: 'not-tuning',
  vhostSniTestL7: 'not-tuning',
  vhostSniUseDefaultWordlist: 'wordlist',
  vhostSniUseGraphCandidates: 'not-tuning',
  wafAiClassifier: 'llm',
  wappalyzerAutoUpdate: 'not-tuning',
  wappalyzerCacheTtlHours: 'not-tuning',
  wappalyzerMinConfidence: 'not-tuning',
  wappalyzerNpmVersion: 'egress',
  wappalyzerRequireHtml: 'not-tuning',
  webCachePoisonAllowCpdos: 'attack',
  webCachePoisonAllowDeception: 'attack',
  webCachePoisonAllowFrameworkPacks: 'attack',
  webCachePoisonBehavioralDelay: 'attack',
  webCachePoisonBehavioralOracle: 'attack',
  webCachePoisonCacheBusterParam: 'attack',
  webCachePoisonCacheHeader: 'attack',
  webCachePoisonConcurrency: 'attack',
  webCachePoisonConfirmWorkers: 'attack',
  webCachePoisonCrossVantage: 'attack',
  webCachePoisonDifferential: 'attack',
  webCachePoisonDockerImage: 'image',
  webCachePoisonEnabled: 'attack',
  webCachePoisonMaxRpsPerHost: 'attack',
  webCachePoisonMinConfidence: 'attack',
  webCachePoisonScanProfile: 'attack',
  webCachePoisonTimeout: 'attack',
  webCachePoisonTimeoutPerReq: 'attack',
  webCachePoisonVerifySsl: 'attack',
  zapAjaxSpiderBrowserId: 'not-tuning',
  zapAjaxSpiderClickDefaultElems: 'not-tuning',
  zapAjaxSpiderClickElemsOnce: 'not-tuning',
  zapAjaxSpiderCustomHeaders: 'headers',
  zapAjaxSpiderDockerImage: 'image',
  zapAjaxSpiderEventWait: 'not-tuning',
  zapAjaxSpiderExcludePatterns: 'not-tuning',
  zapAjaxSpiderLogoutAvoidance: 'not-tuning',
  zapAjaxSpiderMaxCrawlDepth: 'unbounded',
  zapAjaxSpiderMaxCrawlStates: 'not-tuning',
  zapAjaxSpiderMaxDuration: 'not-tuning',
  zapAjaxSpiderMaxUrls: 'unbounded',
  zapAjaxSpiderNumberOfBrowsers: 'not-tuning',
  zapAjaxSpiderParallelism: 'not-tuning',
  zapAjaxSpiderRandomInputs: 'not-tuning',
  zapAjaxSpiderReloadWait: 'not-tuning',
  zapAjaxSpiderScopeCheck: 'not-tuning',
  zapAjaxSpiderSeedMode: 'not-tuning',
})
